# Generated by Django 2.2.6 on 2021-07-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djantimat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceBrowser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.CharField(max_length=254, verbose_name='Отпечаток браузера')),
            ],
            options={
                'verbose_name': 'Отпечаток браузера',
                'verbose_name_plural': 'Отпечатки браузеров',
                'ordering': ['-id'],
            },
        ),
    ]
